using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Character_Names : MonoBehaviour
{
    public static string Character_Names(CharacterArtCode characterArtCode)
    {
        string[] firstNames = new string[]
        {
            "李",
            "王",
            "张",
            "刘",
            "陈",
            "吴",
            "周",
            "徐",
            "马",
            "高",
            "宋",
            "唐",
            "叶",
            "赵",
            "钱",
            "白"
        };
        string[] maleLastNames = new string[]
        {
            "宇",
            "东",
            "胜",
            "谦",
            "清",
            "展",
            "昊",
            "俊",
            "镰",
            "凡",
            "逸",
            "泽",
            "伟",
            "超",
            "涛",
            "杰",
            "鹏",
            "磊",
            "强",
            "浩",
            "鑫",
            "勇",
            "明敬",
            "建义",
            "思远",
            "光华",
            "华清",
            "大柱",
            "生笙",
            "以兵",
            "一",
            "二",
            "三",
            "五",
            "七",
            "晓明",
            "小明",
            "汉",
            "沛",
            "心",
            "宏才",
            "自惟",
            "一帆",
            "宇凡",
            "川旭",
            "柏钧",
            "才",
            "良",
            "权",
        };
        string[] femaleLastNames = new string[]
        {
            "月",
            "可",
            "青",
            "沁",
            "瑶",
            "翠",
            "花",
            "雨",
            "蓉",
            "钰",
            "玉",
            "雪",
            "梓玥",
            "婉怡",
            "菁菁",
            "可心",
            "雨雪",
            "安安",
            "文敏",
            "思语",
            "若",
            "然",
            "琪",
            "静",
            "妍",
            "萱",
            "彤",
            "诗思",
            "诗虞",
            "诗琴",
            "诗琪",
            "诗梦",
            "诗怡",
            "佩文",
            "佩琳",
            "雪嫣",
            "晴雪",
            "馨宁",
            "乐馨",
            "馨月",
            "馨兰",
            "雯洁",
            "雯茜",
            "晴雯",
            "晓雯",
            "雯婷",
            "雯文",
            "艺昕",
            "艺芷"
        };
        string maleName = firstNames[Random.Range(0, firstNames.Length - 1)] + maleLastNames[Random.Range(0, maleLastNames.Length - 1)];
        string femaleName = firstNames[Random.Range(0, firstNames.Length - 1)] + maleLastNames[Random.Range(0, femaleLastNames.Length - 1)];
        List<CharacterArtCode> maleCharacterArtCode = new List<CharacterArtCode>
        {
            CharacterArtCode.男书生,
            CharacterArtCode.老者,
            CharacterArtCode.男刀客,
            CharacterArtCode.男官,
            CharacterArtCode.男官,
            CharacterArtCode.男武,
            CharacterArtCode.琴师,
            CharacterArtCode.说书人,
            CharacterArtCode.棋圣,
            CharacterArtCode.方丈,
            CharacterArtCode.官员,
            CharacterArtCode.拾荒者,
            CharacterArtCode.太监
        };
        if (maleCharacterArtCode.Contains(characterArtCode))
        {
            return maleName;
        }
        else
        {
            return femaleName;
        }
    }
}
